version: '3'
services:
  loa-bot:
    build: .
    #image: python:latest
    #workingdir: /
    #command: bash -c "pip3 install -r requirements.txt && python3 lfg.py"
    volumes:
      - bot-data:/data
      - bot-ressources:/ressources

volumes:
  bot-data:
    external: True
  bot-ressources:
    external: True