version: '3'
services:
  loa-bot:
    build: .
    #image: python:latest
    #workingdir: /
    #command: bash -c "pip3 install -r requirements.txt && python3 lfg.py"
    environment:
      - TOKEN=
      - DB_USER=
      - DB_PW=
      - DB_IP=
      - DB_PORT=
      - DB_NAME=

    volumes:
      - bot-data:/data
      - bot-ressources:/ressources

volumes:
  bot-data:
    external: True
  bot-ressources:
    external: True