version: '3'
services:
  loa-bot:
    build: .
    #image: python:latest
    #workingdir: /
    #command: bash -c "pip3 install -r requirements.txt && python3 lfg.py"
    volumes:
      - ~/docker-files/bot-data:/data
      - ~/docker-diles/bot-ressources:/ressources
